version: '3.8'

services:
  app:
    build:
      context: .
    container_name: customer-crud-api
    ports:
      - '3000:3000'
    environment:
      - SYNCHRONIZE_DB=true
      - URL_ZIPCODE_API=https://cep.awesomeapi.com.br/json/

    command: ['yarn', 'start']
